export {
  createCompany,
  updateCompany,
  deleteCompany,
  getCompany,
  listCompanies,
  listMembers,
  getActivityCounts,
  getForPrincipal,
  attachPrincipal,
  detachPrincipal,
  qualifyCompany,
} from './company.service'
export type {
  Company,
  CompanyId,
  CompanyWithMemberCount,
  CompanyListFilter,
  CompanyAttrFilter,
  CompanyMember,
  CompanyActivityCounts,
  CreateCompanyInput,
  UpdateCompanyInput,
  QualifyCompanyInput,
} from './company.types'
