/**
 * Cloudflare environment augmentation for job processing.
 *
 * This extends the base Cloudflare.Env interface generated by wrangler
 * to include workflow and durable object bindings.
 *
 * After updating wrangler.jsonc, run `wrangler types` to regenerate
 * worker-configuration.d.ts with the new bindings.
 */

import type {
  Workflow,
  DurableObjectNamespace,
  Hyperdrive,
  Fetcher,
} from '@cloudflare/workers-types'
import type {
  ImportJobData,
  IntegrationJobData,
  UserNotificationJobData,
  ImportJobResult,
  IntegrationJobResult,
  UserNotificationJobResult,
} from '@quackback/jobs/types'

// Augment the global CloudflareEnv interface
declare global {
  interface CloudflareEnv {
    // Database connection via Hyperdrive
    HYPERDRIVE: Hyperdrive

    // Self-reference for internal service binding calls
    WORKER_SELF_REFERENCE: Fetcher

    // Job processing workflows
    IMPORT_WORKFLOW: Workflow<ImportJobData, ImportJobResult>
    INTEGRATION_WORKFLOW: Workflow<IntegrationJobData, IntegrationJobResult>
    NOTIFICATION_WORKFLOW: Workflow<UserNotificationJobData, UserNotificationJobResult>

    // State management durable objects
    INTEGRATION_STATE: DurableObjectNamespace
  }
}

export {}
