/**
 * Email sending module for Quackback
 *
 * Uses pre-rendered HTML templates (built at compile time from React Email components)
 * with runtime string interpolation. This approach works reliably on both Node.js
 * and Cloudflare Workers without React/Prettier bundling issues.
 *
 * Templates are generated by: bun run build:templates
 */

import { templates } from '../dist/templates'

const FROM_EMAIL = process.env.EMAIL_FROM || 'Quackback <noreply@quackback.io>'

// Check if we should log emails to console instead of sending
function shouldLogToConsole(): boolean {
  return process.env.DEV_EMAIL_TO_CONSOLE === 'true'
}

// Simple template interpolation - replaces {{key}} with values
function interpolate(template: string, values: Record<string, string>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => values[key] ?? '')
}

// Send email via Resend API using fetch (works in both Node.js and Cloudflare Workers)
async function sendEmail({ to, subject, html }: { to: string; subject: string; html: string }) {
  const apiKey = process.env.RESEND_API_KEY
  if (!apiKey) {
    throw new Error('RESEND_API_KEY environment variable is not set')
  }

  const response = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: FROM_EMAIL,
      to,
      subject,
      html,
    }),
  })

  if (!response.ok) {
    const error = await response.json()
    throw new Error(`Failed to send email via Resend: ${JSON.stringify(error)}`)
  }

  return response.json()
}

// ============================================================================
// Invitation Email
// ============================================================================

interface SendInvitationParams {
  to: string
  invitedByName: string
  inviteeName?: string
  workspaceName: string
  inviteLink: string
}

export async function sendInvitationEmail(params: SendInvitationParams) {
  const { to, invitedByName, inviteeName, workspaceName, inviteLink } = params

  if (shouldLogToConsole()) {
    console.log('\n┌────────────────────────────────────────────────────────────')
    console.log('│ [DEV] Invitation Email')
    console.log('├────────────────────────────────────────────────────────────')
    console.log(`│ To: ${to}`)
    console.log(`│ Invitee name: ${inviteeName || '(not provided)'}`)
    console.log(`│ Invited by: ${invitedByName}`)
    console.log(`│ Workspace: ${workspaceName}`)
    console.log(`│ Invite link: ${inviteLink}`)
    console.log('└────────────────────────────────────────────────────────────\n')
    return
  }

  const html = interpolate(templates.invitation, {
    invitedByName,
    inviteeName: inviteeName || '',
    organizationName: workspaceName,
    inviteLink,
  })

  await sendEmail({
    to,
    subject: `You've been invited to join ${workspaceName} on Quackback`,
    html,
  })
}

// ============================================================================
// Welcome Email
// ============================================================================

interface SendWelcomeParams {
  to: string
  name: string
  workspaceName: string
  dashboardUrl: string
}

export async function sendWelcomeEmail(params: SendWelcomeParams) {
  const { to, name, workspaceName, dashboardUrl } = params

  if (shouldLogToConsole()) {
    console.log('\n┌────────────────────────────────────────────────────────────')
    console.log('│ [DEV] Welcome Email')
    console.log('├────────────────────────────────────────────────────────────')
    console.log(`│ To: ${to}`)
    console.log(`│ Name: ${name}`)
    console.log(`│ Workspace: ${workspaceName}`)
    console.log(`│ Dashboard: ${dashboardUrl}`)
    console.log('└────────────────────────────────────────────────────────────\n')
    return
  }

  const html = interpolate(templates.welcome, {
    name,
    workspaceName,
    dashboardUrl,
  })

  await sendEmail({
    to,
    subject: `Welcome to ${workspaceName} on Quackback!`,
    html,
  })
}

// ============================================================================
// Sign-in Code Email
// ============================================================================

interface SendSigninCodeParams {
  to: string
  code: string
}

export async function sendSigninCodeEmail(params: SendSigninCodeParams) {
  const { to, code } = params

  if (shouldLogToConsole()) {
    console.log('\n┌────────────────────────────────────────────────────────────')
    console.log('│ [DEV] Sign-in Code Email')
    console.log('├────────────────────────────────────────────────────────────')
    console.log(`│ To: ${to}`)
    console.log(`│ Code: ${code}`)
    console.log('└────────────────────────────────────────────────────────────\n')
    return
  }

  const html = interpolate(templates.signinCode, { code })

  await sendEmail({
    to,
    subject: `Your Quackback sign-in code is ${code}`,
    html,
  })
}

// ============================================================================
// Status Change Email
// ============================================================================

interface SendStatusChangeParams {
  to: string
  postTitle: string
  postUrl: string
  previousStatus: string
  newStatus: string
  workspaceName: string
  unsubscribeUrl: string
}

export async function sendStatusChangeEmail(params: SendStatusChangeParams) {
  const { to, postTitle, postUrl, previousStatus, newStatus, workspaceName, unsubscribeUrl } =
    params

  if (shouldLogToConsole()) {
    console.log('\n┌────────────────────────────────────────────────────────────')
    console.log('│ [DEV] Status Change Email')
    console.log('├────────────────────────────────────────────────────────────')
    console.log(`│ To: ${to}`)
    console.log(`│ Post: ${postTitle}`)
    console.log(`│ Status: ${previousStatus} → ${newStatus}`)
    console.log(`│ URL: ${postUrl}`)
    console.log(`│ Unsubscribe: ${unsubscribeUrl}`)
    console.log('└────────────────────────────────────────────────────────────\n')
    return
  }

  const formattedStatus = newStatus.replace(/_/g, ' ')

  const html = interpolate(templates.statusChange, {
    postTitle,
    postUrl,
    previousStatus: previousStatus.replace(/_/g, ' '),
    newStatus: formattedStatus,
    organizationName: workspaceName,
    unsubscribeUrl,
  })

  await sendEmail({
    to,
    subject: `Your feedback is now ${formattedStatus}!`,
    html,
  })
}

// ============================================================================
// New Comment Email
// ============================================================================

interface SendNewCommentParams {
  to: string
  postTitle: string
  postUrl: string
  commenterName: string
  commentPreview: string
  isTeamMember: boolean
  workspaceName: string
  unsubscribeUrl: string
}

export async function sendNewCommentEmail(params: SendNewCommentParams) {
  const {
    to,
    postTitle,
    postUrl,
    commenterName,
    commentPreview,
    isTeamMember,
    workspaceName,
    unsubscribeUrl,
  } = params

  if (shouldLogToConsole()) {
    console.log('\n┌────────────────────────────────────────────────────────────')
    console.log('│ [DEV] New Comment Email')
    console.log('├────────────────────────────────────────────────────────────')
    console.log(`│ To: ${to}`)
    console.log(`│ Post: ${postTitle}`)
    console.log(`│ From: ${commenterName}${isTeamMember ? ' (Team)' : ''}`)
    console.log(`│ Comment: ${commentPreview.substring(0, 50)}...`)
    console.log(`│ URL: ${postUrl}`)
    console.log(`│ Unsubscribe: ${unsubscribeUrl}`)
    console.log('└────────────────────────────────────────────────────────────\n')
    return
  }

  // Use the appropriate template variant based on team membership
  const template = isTeamMember ? templates.newCommentTeam : templates.newComment

  const html = interpolate(template, {
    postTitle,
    postUrl,
    commenterName,
    commentPreview,
    organizationName: workspaceName,
    unsubscribeUrl,
  })

  await sendEmail({
    to,
    subject: `New comment on "${postTitle}"`,
    html,
  })
}

// ============================================================================
// Re-export templates for preview/testing
// ============================================================================

export { InvitationEmail } from './templates/invitation'
export { WelcomeEmail } from './templates/welcome'
export { SigninCodeEmail } from './templates/signin-code'
export { StatusChangeEmail } from './templates/status-change'
export { NewCommentEmail } from './templates/new-comment'
