/**
 * Inbound email parsing: normalize Resend's `email.received` payload into the
 * fields the ingest path needs, and strip quoted reply history so the ingested
 * message is just what the visitor actually wrote.
 */
import { describe, it, expect } from 'vitest'
import {
  parseInboundEmail,
  parseRawEmail,
  extractReplyText,
  extractEmailAddress,
  parseMessageIdList,
  messageIdDomain,
  isAutoGeneratedEmail,
  type ParsedInboundEmail,
} from '../conversation.email-inbound'

describe('parseInboundEmail', () => {
  it('normalizes an array `to`, reads `from`/`subject`/`text`, and the Message-ID header', () => {
    const parsed = parseInboundEmail({
      to: ['reply+conversation_abc@tenaevexeo.resend.app'],
      from: 'Jane Visitor <jane@example.com>',
      subject: 'Re: Your ticket',
      text: 'Thanks, that worked!',
      headers: [
        { name: 'Message-ID', value: '<msg-123@mail.example.com>' },
        { name: 'X-Other', value: 'ignored' },
      ],
    })
    expect(parsed.toAddresses).toEqual(['reply+conversation_abc@tenaevexeo.resend.app'])
    expect(parsed.from).toBe('Jane Visitor <jane@example.com>')
    expect(parsed.subject).toBe('Re: Your ticket')
    expect(parsed.text).toBe('Thanks, that worked!')
    expect(parsed.messageId).toBe('<msg-123@mail.example.com>')
  })

  it('accepts a string `to` and an object-shaped headers map (case-insensitive)', () => {
    const parsed = parseInboundEmail({
      to: 'reply+conversation_xyz@tenaevexeo.resend.app',
      from: 'bob@example.com',
      headers: { 'message-id': '<abc@x>' },
    })
    expect(parsed.toAddresses).toEqual(['reply+conversation_xyz@tenaevexeo.resend.app'])
    expect(parsed.messageId).toBe('<abc@x>')
  })

  it('falls back to the top-level email id when no Message-ID header is present', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      from: 'a@b.com',
      email_id: 'email_fallback_1',
    })
    expect(parsed.messageId).toBe('email_fallback_1')
  })

  it('returns empty/null fields for a junk payload rather than throwing', () => {
    const parsed = parseInboundEmail(null)
    expect(parsed.toAddresses).toEqual([])
    expect(parsed.from).toBeNull()
    expect(parsed.messageId).toBeNull()
    expect(parsed.inReplyTo).toBeNull()
    expect(parsed.references).toEqual([])
    expect(parsed.html).toBeUndefined()
  })

  it('reads the html body field alongside text when a payload carries both', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      text: 'plain body',
      html: '<p>rich body</p>',
    })
    expect(parsed.text).toBe('plain body')
    expect(parsed.html).toBe('<p>rich body</p>')
  })

  it('reads the html body field when the payload has no plain-text field', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      html: '<p>only html</p>',
    })
    expect(parsed.text).toBeNull()
    expect(parsed.html).toBe('<p>only html</p>')
  })

  it('leaves html undefined when the payload has no html field', () => {
    const parsed = parseInboundEmail({ to: ['x@y.com'], text: 'plain only' })
    expect(parsed.html).toBeUndefined()
  })

  it('reads the threading + auto-mail headers', () => {
    const parsed = parseInboundEmail({
      to: ['x@y.com'],
      headers: [
        { name: 'In-Reply-To', value: '<a@d>' },
        { name: 'References', value: '<a@d> <b@d>' },
        { name: 'Auto-Submitted', value: 'auto-replied' },
        { name: 'Precedence', value: 'bulk' },
        { name: 'List-Id', value: 'news.example' },
      ],
    })
    expect(parsed.inReplyTo).toBe('a@d')
    expect(parsed.references).toEqual(['a@d', 'b@d'])
    expect(parsed.autoSubmitted).toBe('auto-replied')
    expect(parsed.precedence).toBe('bulk')
    expect(parsed.hasListHeaders).toBe(true)
  })

  it('captures cc recipients (array or string), empty when absent', () => {
    expect(parseInboundEmail({ to: 'x@y.com', cc: ['a@c.com', 'b@c.com'] }).ccAddresses).toEqual([
      'a@c.com',
      'b@c.com',
    ])
    expect(parseInboundEmail({ to: 'x@y.com', cc: 'solo@c.com' }).ccAddresses).toEqual([
      'solo@c.com',
    ])
    expect(parseInboundEmail({ to: 'x@y.com' }).ccAddresses).toEqual([])
  })
})

describe('parseRawEmail', () => {
  it('parses headers and a plain-text body from a raw RFC822 message', () => {
    const raw = [
      'From: Jane Visitor <jane@example.com>',
      'To: reply+conversation_abc.sig@tenaevexeo.resend.app',
      'Subject: Re: ticket',
      'Message-ID: <m-1@example.com>',
      'In-Reply-To: <c.abc.n1@tenaevexeo.resend.app>',
      'References: <c.abc.n0@tenaevexeo.resend.app> <c.abc.n1@tenaevexeo.resend.app>',
      '',
      'This is my reply.',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.from).toBe('Jane Visitor <jane@example.com>')
    expect(parsed.toAddresses).toEqual(['reply+conversation_abc.sig@tenaevexeo.resend.app'])
    expect(parsed.subject).toBe('Re: ticket')
    expect(parsed.messageId).toBe('<m-1@example.com>')
    expect(parsed.inReplyTo).toBe('c.abc.n1@tenaevexeo.resend.app')
    expect(parsed.references).toEqual([
      'c.abc.n0@tenaevexeo.resend.app',
      'c.abc.n1@tenaevexeo.resend.app',
    ])
    expect(parsed.text).toBe('This is my reply.')
    expect(parsed.html).toBeUndefined()
  })

  it('unfolds a folded header (continuation line)', () => {
    const raw = ['Subject: a very long', ' folded subject', '', 'body'].join('\r\n')
    expect(parseRawEmail(raw).subject).toBe('a very long folded subject')
  })

  it('parses Cc recipients from the header', () => {
    const raw = [
      'To: support@acme.com',
      'Cc: alice@example.com, Bob <bob@example.com>',
      '',
      'body',
    ].join('\r\n')
    expect(parseRawEmail(raw).ccAddresses).toEqual(['alice@example.com', 'Bob <bob@example.com>'])
  })

  it('decodes a quoted-printable body', () => {
    const raw = [
      'Content-Type: text/plain',
      'Content-Transfer-Encoding: quoted-printable',
      '',
      'Caf=C3=A9 time =\n now',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text).toBe('Café time  now')
    expect(parsed.html).toBeUndefined()
  })

  it('extracts both text/plain and text/html parts of a multipart/alternative message, one quoted-printable', () => {
    const raw = [
      'Content-Type: multipart/alternative; boundary="B"',
      '',
      '--B',
      'Content-Type: text/plain',
      '',
      'plain body here',
      '--B',
      'Content-Type: text/html',
      'Content-Transfer-Encoding: quoted-printable',
      '',
      '<p>Caf=C3=A9 html body</p>',
      '--B--',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text?.trim()).toBe('plain body here')
    expect(parsed.html?.trim()).toBe('<p>Café html body</p>')
  })

  it('extracts the html part of an HTML-only (non-multipart) message', () => {
    const raw = [
      'Content-Type: text/html; charset=utf-8',
      '',
      '<p>Only an HTML body here.</p>',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text).toBe('')
    expect(parsed.html).toBe('<p>Only an HTML body here.</p>')
  })

  it('extracts the html part of a multipart message with no text/plain part', () => {
    const raw = [
      'Content-Type: multipart/alternative; boundary="B"',
      '',
      '--B',
      'Content-Type: text/html',
      '',
      '<p>html-only alternative</p>',
      '--B--',
    ].join('\r\n')
    const parsed = parseRawEmail(raw)
    expect(parsed.text).toBe('')
    expect(parsed.html?.trim()).toBe('<p>html-only alternative</p>')
  })
})

describe('parseMessageIdList', () => {
  it('extracts all angle-bracketed ids, bare and trimmed', () => {
    expect(parseMessageIdList('<a@d>  <b@d>')).toEqual(['a@d', 'b@d'])
  })
  it('falls back to a bare, whitespace-free value', () => {
    expect(parseMessageIdList('bare@d')).toEqual(['bare@d'])
  })
  it('returns [] for null or a value with no usable id', () => {
    expect(parseMessageIdList(null)).toEqual([])
    expect(parseMessageIdList('no ids here')).toEqual([])
  })
})

describe('messageIdDomain', () => {
  it('reads the domain from an angle-bracketed or bare id', () => {
    expect(messageIdDomain('<x@Mail.Example.com>')).toBe('mail.example.com')
    expect(messageIdDomain('x@d')).toBe('d')
    expect(messageIdDomain(null)).toBeNull()
  })
})

describe('isAutoGeneratedEmail', () => {
  const base: ParsedInboundEmail = {
    toAddresses: [],
    ccAddresses: [],
    from: 'a@b.com',
    subject: null,
    text: 'hi',
    messageId: '<m@sender.example>',
    inReplyTo: null,
    references: [],
    autoSubmitted: null,
    autoResponseSuppress: null,
    precedence: null,
    hasListHeaders: false,
    authenticationResults: null,
  }

  it('passes an ordinary human reply', () => {
    expect(isAutoGeneratedEmail(base)).toBe(false)
    expect(isAutoGeneratedEmail({ ...base, autoSubmitted: 'no' })).toBe(false)
  })

  it('drops auto-submitted, suppressed, bulk/junk/list, and list mail', () => {
    expect(isAutoGeneratedEmail({ ...base, autoSubmitted: 'auto-replied' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, autoResponseSuppress: 'All' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, precedence: 'bulk' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, precedence: 'junk' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, precedence: 'list' })).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, hasListHeaders: true })).toBe(true)
  })

  it('drops our own mail looping back (Message-ID on one of our domains)', () => {
    const ownDomains = new Set(['sender.example'])
    expect(isAutoGeneratedEmail(base, ownDomains)).toBe(true)
    expect(isAutoGeneratedEmail({ ...base, messageId: '<m@other.example>' }, ownDomains)).toBe(
      false
    )
  })
})

describe('extractReplyText', () => {
  it('drops a Gmail-style quoted history below "On … wrote:"', () => {
    const raw = [
      'This is my reply.',
      '',
      'On Mon, Jun 1, 2026 at 9:00 AM Support <reply+x@d> wrote:',
      '> previous agent message',
      '> more quoted text',
    ].join('\n')
    expect(extractReplyText(raw)).toBe('This is my reply.')
  })

  it('drops a leading-`>` quoted block with no separator line', () => {
    const raw = ['My answer is here.', '> quoted', '> quoted 2'].join('\n')
    expect(extractReplyText(raw)).toBe('My answer is here.')
  })

  it('strips a trailing signature after the "-- " delimiter', () => {
    const raw = ['Sounds good.', '', '-- ', 'Jane Visitor', 'Acme Inc'].join('\n')
    expect(extractReplyText(raw)).toBe('Sounds good.')
  })

  it('leaves a plain reply untouched (trimmed)', () => {
    expect(extractReplyText('  just a normal reply  ')).toBe('just a normal reply')
  })

  it('keeps a reply that begins with a "From:" prose line (not a forwarded header)', () => {
    expect(extractReplyText('From: my perspective this is broken\nplease help')).toBe(
      'From: my perspective this is broken\nplease help'
    )
  })

  it('keeps prose that merely contains a mid-body "From:" line', () => {
    const raw = 'I have two questions.\n\nFrom: the docs it says X\nCan you clarify?'
    expect(extractReplyText(raw)).toBe(raw)
  })

  it('falls back to the visitor text when a quote separator lands on the first line', () => {
    // Some clients put the attribution line first; cutting at it would drop the
    // whole message, so we recover the non-quoted text instead of returning "".
    expect(extractReplyText('On Mon, Jun 1, 2026 someone wrote:\nThanks, this is fixed now!')).toBe(
      'Thanks, this is fixed now!'
    )
  })

  it('still returns empty for a reply that is entirely quoted history', () => {
    expect(extractReplyText('On Mon wrote:\n> only quoted text\n> more quoted')).toBe('')
  })
})

describe('extractEmailAddress', () => {
  it('returns a bare address lowercased and trimmed', () => {
    expect(extractEmailAddress(' Jane@Example.COM ')).toBe('jane@example.com')
  })

  it('extracts the addr-spec from a name-addr From header', () => {
    expect(extractEmailAddress('Jane Visitor <Jane@Example.com>')).toBe('jane@example.com')
  })

  it('handles a quoted display name containing a comma', () => {
    expect(extractEmailAddress('"Doe, Jane" <jane@example.com>')).toBe('jane@example.com')
  })

  it('returns null for null, empty, or address-less input', () => {
    expect(extractEmailAddress(null)).toBeNull()
    expect(extractEmailAddress('')).toBeNull()
    expect(extractEmailAddress('not an address')).toBeNull()
  })

  it('returns null for malformed addr-specs', () => {
    expect(extractEmailAddress('Jane <@example.com>')).toBeNull()
    expect(extractEmailAddress('Jane <jane@>')).toBeNull()
    expect(extractEmailAddress('a@b@c')).toBeNull()
  })
})
