/**
 * Build script to pre-render React email templates to HTML
 *
 * This runs at build time (in Node.js) to generate static HTML templates
 * with {{placeholder}} syntax for runtime interpolation.
 *
 * The output can be used in Cloudflare Workers without any React/Prettier dependencies.
 *
 * Usage: bun run build:templates
 */

import { render } from '@react-email/render'
import { writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

// Import templates
import { SigninCodeEmail } from '../src/templates/signin-code'
import { InvitationEmail } from '../src/templates/invitation'
import { WelcomeEmail } from '../src/templates/welcome'
import { StatusChangeEmail } from '../src/templates/status-change'
import { NewCommentEmail } from '../src/templates/new-comment'

const __dirname = dirname(fileURLToPath(import.meta.url))
const distDir = join(__dirname, '../dist')

// Ensure dist directory exists
mkdirSync(distDir, { recursive: true })

// Render templates with placeholder values
async function buildTemplates() {
  console.log('Building email templates...')

  const templates: Record<string, string> = {}

  // Sign-in code template
  templates.signinCode = await render(SigninCodeEmail({ code: '{{code}}' }), { pretty: false })

  // Invitation template
  templates.invitation = await render(
    InvitationEmail({
      invitedByName: '{{invitedByName}}',
      inviteeName: '{{inviteeName}}',
      organizationName: '{{organizationName}}',
      inviteLink: '{{inviteLink}}',
    }),
    { pretty: false }
  )

  // Welcome template
  templates.welcome = await render(
    WelcomeEmail({
      name: '{{name}}',
      workspaceName: '{{workspaceName}}',
      dashboardUrl: '{{dashboardUrl}}',
    }),
    { pretty: false }
  )

  // Status change template
  templates.statusChange = await render(
    StatusChangeEmail({
      postTitle: '{{postTitle}}',
      postUrl: '{{postUrl}}',
      previousStatus: '{{previousStatus}}',
      newStatus: '{{newStatus}}',
      organizationName: '{{organizationName}}',
      unsubscribeUrl: '{{unsubscribeUrl}}',
    }),
    { pretty: false }
  )

  // New comment template
  templates.newComment = await render(
    NewCommentEmail({
      postTitle: '{{postTitle}}',
      postUrl: '{{postUrl}}',
      commenterName: '{{commenterName}}',
      commentPreview: '{{commentPreview}}',
      isTeamMember: false, // We'll handle this with conditional in runtime
      organizationName: '{{organizationName}}',
      unsubscribeUrl: '{{unsubscribeUrl}}',
    }),
    { pretty: false }
  )

  // Also render team member variant
  templates.newCommentTeam = await render(
    NewCommentEmail({
      postTitle: '{{postTitle}}',
      postUrl: '{{postUrl}}',
      commenterName: '{{commenterName}}',
      commentPreview: '{{commentPreview}}',
      isTeamMember: true,
      organizationName: '{{organizationName}}',
      unsubscribeUrl: '{{unsubscribeUrl}}',
    }),
    { pretty: false }
  )

  // Generate TypeScript module with templates
  const output = `// Auto-generated by scripts/build-templates.ts
// Do not edit manually - run 'bun run build:templates' to regenerate

export const templates = {
  signinCode: ${JSON.stringify(templates.signinCode)},
  invitation: ${JSON.stringify(templates.invitation)},
  welcome: ${JSON.stringify(templates.welcome)},
  statusChange: ${JSON.stringify(templates.statusChange)},
  newComment: ${JSON.stringify(templates.newComment)},
  newCommentTeam: ${JSON.stringify(templates.newCommentTeam)},
} as const
`

  writeFileSync(join(distDir, 'templates.ts'), output)
  console.log('Templates built successfully!')
  console.log(`Output: ${join(distDir, 'templates.ts')}`)
}

buildTemplates().catch((err) => {
  console.error('Failed to build templates:', err)
  process.exit(1)
})
