/**
 * Better-auth schema for Drizzle ORM integration.
 *
 * Generated by: bunx @better-auth/cli@latest generate
 * Then customized with timezone-aware timestamps.
 *
 * To regenerate, run from apps/web:
 *   bunx @better-auth/cli@latest generate
 *
 * @see https://www.better-auth.com/docs/adapters/drizzle
 */
import { relations } from 'drizzle-orm'
import {
  pgTable,
  text,
  timestamp,
  boolean,
  index,
  uniqueIndex,
  customType,
} from 'drizzle-orm/pg-core'

// Custom type for PostgreSQL bytea (binary data)
const bytea = customType<{ data: Buffer | null; notNull: false; default: false }>({
  dataType() {
    return 'bytea'
  },
  toDriver(value: Buffer | null): Buffer | null {
    return value
  },
  fromDriver(value: unknown): Buffer | null {
    if (value === null || value === undefined) {
      return null
    }
    if (Buffer.isBuffer(value)) {
      return value
    }
    if (value instanceof Uint8Array) {
      return Buffer.from(value)
    }
    // Handle hex string format from postgres.js (e.g., '\xDEADBEEF')
    if (typeof value === 'string') {
      if (value.startsWith('\\x')) {
        return Buffer.from(value.slice(2), 'hex')
      }
      // Empty string means no data
      if (value === '') {
        return null
      }
    }
    // For any other unexpected format, return null rather than crashing
    console.warn('Unexpected bytea format from database:', typeof value)
    return null
  },
})

/**
 * User table - Organization-scoped user identities
 *
 * Each user belongs to exactly one organization. The same email can exist
 * in multiple organizations as separate user records with separate credentials.
 *
 * This enables true multi-tenant isolation where each organization has
 * completely independent authentication.
 */
export const user = pgTable(
  'user',
  {
    id: text('id').primaryKey(),
    // Organization this user belongs to - enables org-scoped email uniqueness
    organizationId: text('organization_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    email: text('email').notNull(),
    emailVerified: boolean('email_verified').default(false).notNull(),
    image: text('image'),
    // Profile image stored as blob (alternative to URL in 'image' field)
    imageBlob: bytea('image_blob'),
    imageType: text('image_type'), // MIME type: image/jpeg, image/png, etc.
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
    // General user metadata (JSON)
    metadata: text('metadata'),
  },
  (table) => [
    // Email is unique per organization (not globally)
    uniqueIndex('user_email_org_idx').on(table.organizationId, table.email),
    index('user_org_id_idx').on(table.organizationId),
  ]
)

export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    activeOrganizationId: text('active_organization_id'),
  },
  (table) => [index('session_userId_idx').on(table.userId)]
)

export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('account_userId_idx').on(table.userId)]
)

export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)]
)

export const organization = pgTable('organization', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  slug: text('slug').notNull().unique(),
  logo: text('logo'),
  // Logo stored as blob (alternative to URL in 'logo' field)
  logoBlob: bytea('logo_blob'),
  logoType: text('logo_type'), // MIME type: image/jpeg, image/png, etc.
  createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  metadata: text('metadata'),
  /**
   * Team authentication configuration (JSON)
   * @see AuthConfig in organization.types.ts
   * Structure: { oauth: { google, github, microsoft }, ssoRequired, openSignup }
   */
  authConfig: text('auth_config'),
  /**
   * Portal configuration (JSON)
   * @see PortalConfig in organization.types.ts
   * Structure: { oauth: { google, github }, features: { publicView, submissions, comments, voting } }
   */
  portalConfig: text('portal_config'),
  /**
   * Branding/theme configuration (JSON)
   * @see BrandingConfig in organization.types.ts
   * Structure: { preset?, light?: ThemeColors, dark?: ThemeColors }
   */
  brandingConfig: text('branding_config'),
})

/**
 * Member table - Unified membership for all user types
 *
 * All users (team members and portal users) have a member record with a role:
 * - 'owner': Full administrative access, can manage billing and delete org
 * - 'admin': Administrative access, can manage team and settings
 * - 'member': Team member access, can manage feedback
 * - 'user': Portal user access only, can vote/comment on public portal
 *
 * The role determines access level: owner/admin/member can access /admin dashboard,
 * while 'user' role can only interact with the public portal.
 */
export const member = pgTable(
  'member',
  {
    id: text('id').primaryKey(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    // Unified roles: 'owner' | 'admin' | 'member' | 'user'
    // 'user' role = portal users (public portal access only, no admin dashboard)
    role: text('role').default('member').notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull(),
  },
  (table) => [
    index('member_organizationId_idx').on(table.organizationId),
    index('member_userId_idx').on(table.userId),
    // Ensure one member record per user per org
    uniqueIndex('member_user_org_idx').on(table.userId, table.organizationId),
    // Composite index for portal user listings filtered by role
    index('member_org_role_idx').on(table.organizationId, table.role),
  ]
)

export const invitation = pgTable(
  'invitation',
  {
    id: text('id').primaryKey(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    email: text('email').notNull(),
    name: text('name'),
    role: text('role'),
    status: text('status').default('pending').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    lastSentAt: timestamp('last_sent_at', { withTimezone: true }),
    inviterId: text('inviter_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (table) => [
    index('invitation_organizationId_idx').on(table.organizationId),
    index('invitation_email_idx').on(table.email),
  ]
)

/**
 * SSO Provider table for Better-Auth SSO plugin
 *
 * Stores SAML and OIDC provider configurations per organization.
 * Used by the SSO plugin to authenticate users via enterprise identity providers.
 *
 * @see https://www.better-auth.com/docs/plugins/sso
 */
export const ssoProvider = pgTable(
  'sso_provider',
  {
    id: text('id').primaryKey(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    // Issuer identifier (e.g., "https://accounts.google.com" or SAML entityId)
    issuer: text('issuer').notNull(),
    // Domain for email-based provider routing (e.g., "acme.com")
    domain: text('domain').notNull(),
    // Unique provider identifier used in login URLs
    providerId: text('provider_id').notNull().unique(),
    // OIDC configuration (JSON): { clientId, clientSecret, discoveryUrl, ... }
    oidcConfig: text('oidc_config'),
    // SAML configuration (JSON): { ssoUrl, certificate, signRequest, ... }
    samlConfig: text('saml_config'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true })
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [
    index('sso_provider_org_id_idx').on(table.organizationId),
    // Domain is unique per organization (not globally) - same domain can be used by different orgs
    uniqueIndex('sso_provider_org_domain_idx').on(table.organizationId, table.domain),
    // Index for SSO detection by email domain
    index('sso_provider_domain_idx').on(table.domain),
  ]
)

// Relations for Drizzle relational queries (enables experimental joins)
export const userRelations = relations(user, ({ one, many }) => ({
  organization: one(organization, {
    fields: [user.organizationId],
    references: [organization.id],
  }),
  sessions: many(session),
  accounts: many(account),
  members: many(member),
  invitations: many(invitation),
  sessionTransferTokens: many(sessionTransferToken),
}))

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, {
    fields: [session.userId],
    references: [user.id],
  }),
}))

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, {
    fields: [account.userId],
    references: [user.id],
  }),
}))

export const organizationRelations = relations(organization, ({ many }) => ({
  users: many(user),
  members: many(member),
  invitations: many(invitation),
  ssoProviders: many(ssoProvider),
  domains: many(workspaceDomain),
}))

export const memberRelations = relations(member, ({ one }) => ({
  organization: one(organization, {
    fields: [member.organizationId],
    references: [organization.id],
  }),
  user: one(user, {
    fields: [member.userId],
    references: [user.id],
  }),
}))

export const invitationRelations = relations(invitation, ({ one }) => ({
  organization: one(organization, {
    fields: [invitation.organizationId],
    references: [organization.id],
  }),
  inviter: one(user, {
    fields: [invitation.inviterId],
    references: [user.id],
  }),
}))

export const ssoProviderRelations = relations(ssoProvider, ({ one }) => ({
  organization: one(organization, {
    fields: [ssoProvider.organizationId],
    references: [organization.id],
  }),
}))

/**
 * Session Transfer Token table for per-subdomain session creation
 *
 * When auth flows happen on the main domain but sessions need to be
 * created on tenant subdomains, this table stores one-time tokens
 * that are exchanged for session cookies on the target subdomain.
 *
 * Used by:
 * - OAuth callbacks (main domain -> subdomain)
 * - Workspace creation (main domain -> new subdomain)
 */
export const sessionTransferToken = pgTable(
  'session_transfer_token',
  {
    id: text('id').primaryKey(),
    token: text('token').notNull().unique(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    targetDomain: text('target_domain').notNull(),
    callbackUrl: text('callback_url').notNull(),
    /** Context for post-login redirect: 'team' -> /admin, 'portal' -> / */
    context: text('context').default('team').notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [index('session_transfer_token_token_idx').on(table.token)]
)

export const sessionTransferTokenRelations = relations(sessionTransferToken, ({ one }) => ({
  user: one(user, {
    fields: [sessionTransferToken.userId],
    references: [user.id],
  }),
}))

/**
 * Workspace Domain table for multi-domain support
 *
 * Each workspace can have multiple domains:
 * - Auto-generated subdomain (e.g., acme.quackback.io)
 * - Custom domains (e.g., feedback.acme.com)
 *
 * The proxy uses this table to resolve which organization a request belongs to.
 */
export const workspaceDomain = pgTable(
  'workspace_domain',
  {
    id: text('id').primaryKey(),
    organizationId: text('organization_id')
      .notNull()
      .references(() => organization.id, { onDelete: 'cascade' }),
    domain: text('domain').notNull().unique(),
    domainType: text('domain_type').notNull(), // 'subdomain' | 'custom'
    isPrimary: boolean('is_primary').default(false).notNull(),
    verified: boolean('verified').default(true).notNull(),
    verificationToken: text('verification_token'),
    createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => [
    index('workspace_domain_org_id_idx').on(table.organizationId),
    // Index for tenant resolution by domain (critical path for every request)
    index('workspace_domain_domain_idx').on(table.domain),
  ]
)

export const workspaceDomainRelations = relations(workspaceDomain, ({ one }) => ({
  organization: one(organization, {
    fields: [workspaceDomain.organizationId],
    references: [organization.id],
  }),
}))
