{{- if .Values.dragonfly.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "quackback.fullname" . }}-dragonfly
  labels:
    {{- include "quackback.labels" . | nindent 4 }}
    app.kubernetes.io/component: dragonfly
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "quackback.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dragonfly
{{- end }}
