{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quackback.fullname" . }}-minio
  labels:
    {{- include "quackback.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
stringData:
  MINIO_ROOT_PASSWORD: {{ include "quackback.minioPassword" . | quote }}
{{- end }}
