{{- if .Values.app.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "quackback.fullname" . }}
  labels:
    {{- include "quackback.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
spec:
  minAvailable: {{ .Values.app.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "quackback.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
{{- end }}
