/**
 * Inbound email ingestion. Provider-neutral: `ingestParsedEmail` owns routing
 * and append, and every front door (the Resend webhook via `ingestInboundEmail`,
 * the IMAP poller) normalizes its input to a `ParsedInboundEmail` and feeds it
 * here. A message is routed into a conversation by its plus-address
 * (`reply+<id>@domain`) first, then — for replies whose client stripped the
 * plus-address — by matching its In-Reply-To/References against our stored
 * outbound Message-IDs. The visitor's stripped reply is appended through the
 * normal visitor-message path, so lifecycle (reopen), realtime publish and
 * offline notification all behave exactly as they do for a widget message.
 *
 * Auto-generated mail (autoresponders, bounces, list blasts, our own loops) is
 * dropped up front. The caller assumes an already-authenticated payload (the
 * webhook route is Svix-verified; IMAP owns the mailbox) and this never throws
 * on an unroutable one — it returns a status the caller maps to an ack + log.
 */
import { db, eq, sql, conversationMessages, conversations, principal, user } from '@/lib/server/db'
import type { ConversationId, PrincipalId } from '@quackback/ids'
import type { Actor } from '@/lib/server/policy/types'
import { normalizePrincipalType } from '@/lib/server/functions/auth-helpers'
import { isBlocked } from '@/lib/server/domains/principals/blocking'
import { realEmail } from '@/lib/shared/anonymous-email'
import {
  parseInboundEmail,
  extractReplyText,
  extractEmailAddress,
  isAutoGeneratedEmail,
  type ParsedInboundEmail,
} from './conversation.email-inbound'
import { conversationIdFromInboundAddress, ownEmailDomains } from './conversation.email-channel'
import { emailHtmlToContent } from '@/lib/server/content/email-html-to-content'
import {
  resolveConversationByMessageIds,
  resolvePrincipalIdByEmail,
} from './conversation.email-store'
import { assertConversationSendRate, ConversationRateLimitError } from './conversation.ratelimit'
import { sendVisitorMessage } from './conversation.service'
import { resolveChannelAccountByRecipient } from '@/lib/server/domains/channel-accounts/channel-account.service'
import {
  resolveColdInboundSender,
  createEmailConversation,
} from './conversation.email-cold-inbound'

export type IngestInboundResult =
  | { status: 'ingested'; conversationId: ConversationId }
  | { status: 'duplicate' }
  | { status: 'no_conversation' }
  | { status: 'empty' }
  | { status: 'from_mismatch' }
  | { status: 'rate_limited' }
  | { status: 'suppressed' }

/** Find the conversation id carried by any recipient plus-address. */
function conversationIdFromRecipients(toAddresses: string[]): string | null {
  for (const addr of toAddresses) {
    const id = conversationIdFromInboundAddress(addr)
    if (id) return id
  }
  return null
}

/**
 * Route + append a parsed inbound email. Provider-neutral core shared by the
 * webhook and the IMAP poller.
 */
export async function ingestParsedEmail(parsed: ParsedInboundEmail): Promise<IngestInboundResult> {
  // Loop / auto-mail suppression before any work: never let an autoresponder or
  // one of our own mails looping back fan out a reply.
  if (isAutoGeneratedEmail(parsed, ownEmailDomains())) return { status: 'suppressed' }

  // Route: plus-address first, then the deterministic-Message-ID fallback for
  // replies whose client dropped the plus-address but kept the threading chain.
  let conversationId = conversationIdFromRecipients(parsed.toAddresses) as ConversationId | null
  if (!conversationId) {
    const candidates = [parsed.inReplyTo, ...parsed.references].filter(
      (id): id is string => id !== null
    )
    conversationId = await resolveConversationByMessageIds(candidates)
  }
  // Not a reply to any existing conversation: it may be a fresh email to one of
  // our inbound routes (§4.8 Layer 2 cold inbound), else there's nothing to do.
  if (!conversationId) return ingestColdInbound(parsed)

  // Idempotency first: a redelivered Message-ID short-circuits before any other
  // read (the common retry case). The partial unique index on
  // (metadata->>'emailMessageId') is the hard backstop; this makes a retry a
  // graceful no-op instead of a unique-violation.
  if (parsed.messageId) {
    const [dupe] = await db
      .select({ id: conversationMessages.id })
      .from(conversationMessages)
      .where(sql`${conversationMessages.metadata} ->> 'emailMessageId' = ${parsed.messageId}`)
      .limit(1)
    if (dupe) return { status: 'duplicate' }
  }

  const conversation = await db.query.conversations.findFirst({
    where: eq(conversations.id, conversationId),
  })
  if (!conversation) return { status: 'no_conversation' }

  const plainText = extractReplyText(parsed.text ?? '')
  // Convert the HTML body (when present) to a rich doc + its plaintext mirror.
  // text/plain keeps precedence for the stored `content` (it's the sender's own
  // quote-trimmed words); the HTML only supplies `contentJson` and, for an
  // HTML-only message, the `content` fallback. An empty conversion of a body
  // that WAS html-only still falls back to the placeholder so nothing is lost.
  const converted = parsed.html ? emailHtmlToContent(parsed.html) : null
  if (!plainText && !parsed.html) return { status: 'empty' }
  const content = plainText || converted?.text || '(no plain-text body)'
  const contentJson = converted?.contentJson ?? null

  const visitorPrincipalId = conversation.visitorPrincipalId as PrincipalId
  const visitor = await db.query.principal.findFirst({
    where: eq(principal.id, visitorPrincipalId),
  })
  if (!visitor) return { status: 'no_conversation' }

  // The transport authenticates the delivery, not the SMTP sender: the reply+
  // address is visible to anyone on the email thread (CC, forward), so without
  // this check any third party could inject messages attributed to the visitor.
  // The From must match an address we know for this visitor — a linked account
  // email, the principal contact email, the captured pre-chat email, or a
  // recorded channel identity that resolves to this same visitor principal.
  // realEmail() keeps synthetic anonymous placeholders out of the set; an empty
  // set with no matching identity means nothing can match.
  const linkedUser = visitor.userId
    ? await db.query.user.findFirst({ where: eq(user.id, visitor.userId) })
    : null
  const knownAddresses = new Set(
    [linkedUser?.email, visitor.contactEmail, conversation.visitorEmail]
      .map((e) => realEmail(e))
      .filter((e): e is string => e !== null)
      .map((e) => e.toLowerCase())
  )
  const sender = extractEmailAddress(parsed.from)
  if (!sender) return { status: 'from_mismatch' }
  if (!knownAddresses.has(sender)) {
    const mappedPrincipalId = await resolvePrincipalIdByEmail(sender)
    if (mappedPrincipalId !== visitorPrincipalId) return { status: 'from_mismatch' }
  }

  // Blocked people cannot reply over email either; ack (200) so the provider
  // stops retrying, mirroring the widget send gate.
  if (await isBlocked(visitorPrincipalId)) return { status: 'suppressed' }

  // Same per-visitor throttle the widget send path enforces — the inbound email
  // channel must not be an unbounded back door for the offline-notification
  // fanout (a visitor mail-looping replies, or a client retrying with fresh
  // Message-IDs). Fails open on Redis errors. Ack (200) so the provider stops.
  try {
    await assertConversationSendRate(visitorPrincipalId)
  } catch (err) {
    if (err instanceof ConversationRateLimitError) return { status: 'rate_limited' }
    throw err
  }

  const actor: Actor = {
    principalId: visitorPrincipalId,
    role: (visitor.role ?? null) as Actor['role'],
    principalType: normalizePrincipalType(visitor.type),
    segmentIds: new Set(),
  }

  await sendVisitorMessage(
    {
      conversationId,
      content,
      metadata: { source: 'email', emailMessageId: parsed.messageId ?? undefined },
    },
    { principalId: visitorPrincipalId, displayName: visitor.displayName },
    actor,
    contentJson
  )

  return { status: 'ingested', conversationId }
}

/**
 * Cold inbound (§4.8 Layer 2): an email that isn't a reply. Only ingest it when
 * it's addressed to one of our inbound routes; otherwise it's not ours. The
 * DMARC-gated sender resolution decides drop / attach / create-lead, then a fresh
 * email conversation is opened. Dedup + empty-body guards mirror the reply path.
 */
async function ingestColdInbound(parsed: ParsedInboundEmail): Promise<IngestInboundResult> {
  const channelAccount = await resolveChannelAccountByRecipient([
    ...parsed.toAddresses,
    ...parsed.ccAddresses,
  ])
  if (!channelAccount || channelAccount.role !== 'inbound') return { status: 'no_conversation' }

  if (parsed.messageId) {
    const [dupe] = await db
      .select({ id: conversationMessages.id })
      .from(conversationMessages)
      .where(sql`${conversationMessages.metadata} ->> 'emailMessageId' = ${parsed.messageId}`)
      .limit(1)
    if (dupe) return { status: 'duplicate' }
  }

  const plainText = extractReplyText(parsed.text ?? '')
  // Same precedence as the reply path: text/plain owns `content`; the HTML body
  // supplies `contentJson` and the HTML-only `content` fallback.
  const converted = parsed.html ? emailHtmlToContent(parsed.html) : null
  if (!plainText && !parsed.html) return { status: 'empty' }
  const content = plainText || converted?.text || '(no plain-text body)'

  const resolution = await resolveColdInboundSender(parsed.from, parsed.authenticationResults)
  if (resolution.action === 'drop') return { status: 'suppressed' }

  const conversationId = await createEmailConversation({
    parsed,
    channelAccountId: channelAccount.id,
    principalId: resolution.principalId,
    unverified: resolution.unverified,
    content,
    contentJson: converted?.contentJson ?? null,
  })
  return { status: 'ingested', conversationId }
}

/**
 * Webhook front door: normalize a provider `email.received` event's parsed
 * `data` and ingest it. Kept as the stable entry point the Resend webhook
 * handler calls.
 */
export async function ingestInboundEmail(event: unknown): Promise<IngestInboundResult> {
  const data =
    (event && typeof event === 'object' ? (event as { data?: unknown }).data : null) ?? null
  return ingestParsedEmail(parseInboundEmail(data))
}
